create opsys.lib
addmod Objs/ACHECK.OBJ 
addmod Objs/ACTIVATE.OBJ 
addmod Objs/ALINK.OBJ 
addmod Objs/ALLCSTAK.OBJ 
addmod Objs/APARSE.OBJ 
addmod Objs/ASSERT.OBJ 
addmod Objs/BASE.OBJ 
addmod Objs/BDOFLUSH.OBJ 
addmod Objs/BGET.OBJ 
addmod Objs/BGETTOKN.OBJ 
addmod Objs/BINNEST.OBJ 
addmod Objs/BITFLAG.OBJ 
addmod Objs/BLKINFO.OBJ 
addmod Objs/BLOCK.OBJ 
addmod Objs/BLOKTASK.OBJ 
addmod Objs/BOUTNEST.OBJ 
addmod Objs/BPUT.OBJ 
addmod Objs/BPUTBACK.OBJ 
addmod Objs/BUFFER.OBJ 
addmod Objs/BWAIT.OBJ 
addmod Objs/CDEBUG.OBJ 
addmod Objs/CEXECUTE.OBJ 
addmod Objs/CHECKINI.OBJ 
addmod Objs/CLKTICK.OBJ 
addmod Objs/CLOCK.OBJ 
addmod Objs/CMDHDR.OBJ 
addmod Objs/CMDHNDLR.OBJ 
addmod Objs/CMDINT.OBJ 
addmod Objs/CMDPIPE.OBJ 
addmod Objs/CMDSUB.OBJ 
addmod Objs/CMDSYS.OBJ 
addmod Objs/CMDTASK.OBJ 
addmod Objs/CNVTAB.OBJ 
addmod Objs/COMMAND.OBJ 
addmod Objs/CPIPE.OBJ 
addmod Objs/CSTART.OBJ 
addmod Objs/CSTOP.OBJ 
addmod Objs/DDOFLUSH.OBJ 
addmod Objs/DEBUG.OBJ 
addmod Objs/DGET.OBJ 
addmod Objs/DOSCHED.OBJ 
addmod Objs/DOSETPRI.OBJ 
addmod Objs/DOTIMOUT.OBJ 
addmod Objs/DPUT.OBJ 
addmod Objs/DPUTBAK1.OBJ 
addmod Objs/DPUTBAK2.OBJ 
addmod Objs/DUNBALL.OBJ 
addmod Objs/EBIN.OBJ 
addmod Objs/EDEC.OBJ 
addmod Objs/EDOFILL.OBJ 
addmod Objs/EDOSETW.OBJ 
addmod Objs/EDOSKIP.OBJ 
addmod Objs/EENDL.OBJ 
addmod Objs/EENDS.OBJ 
addmod Objs/EFAIL.OBJ 
addmod Objs/EFLUSH.OBJ 
addmod Objs/EGCHAR.OBJ 
addmod Objs/EGINT.OBJ 
addmod Objs/EGIOBUF.OBJ 
addmod Objs/EGIOMBOL.OBJ 
addmod Objs/EGIOMCHR.OBJ 
addmod Objs/EGIOMINT.OBJ 
addmod Objs/EGLONG.OBJ 
addmod Objs/EGSHORT.OBJ 
addmod Objs/EGUINT.OBJ 
addmod Objs/EGULONG.OBJ 
addmod Objs/EGUSHORT.OBJ 
addmod Objs/EHEX.OBJ 
addmod Objs/EOCT.OBJ 
addmod Objs/EPCHAR.OBJ 
addmod Objs/EPINT.OBJ 
addmod Objs/EPIOBUF.OBJ 
addmod Objs/EPIOMBOL.OBJ 
addmod Objs/EPIOMCHR.OBJ 
addmod Objs/EPIOMINT.OBJ 
addmod Objs/EPLONG.OBJ 
addmod Objs/EPSHORT.OBJ 
addmod Objs/EPSTRING.OBJ 
addmod Objs/EPULONG.OBJ 
addmod Objs/EPUSHORT.OBJ 
addmod Objs/ESETFILL.OBJ 
addmod Objs/ESETW.OBJ 
addmod Objs/ESKIP.OBJ 
addmod Objs/ESPCFILL.OBJ 
addmod Objs/EUINT.OBJ 
addmod Objs/EXIT.OBJ 
addmod Objs/EXITLATR.OBJ 
addmod Objs/EZROFILL.OBJ 
addmod Objs/FDOFLSH.OBJ 
addmod Objs/FGET.OBJ 
addmod Objs/FPUT.OBJ 
addmod Objs/FPUTBACK.OBJ 
addmod Objs/FSTRING.OBJ 
addmod Objs/FSTRLEN.OBJ 
addmod Objs/GEXECUTE.OBJ 
addmod Objs/HRUN.OBJ 
addmod Objs/ICTL_3XX.OBJ 
addmod Objs/INT_68K.OBJ 
addmod Objs/IOBUF.OBJ 
addmod Objs/IOSTRING.OBJ 
addmod Objs/LINKFREE.OBJ 
addmod Objs/LOCK.OBJ 
addmod Objs/MAGET.OBJ 
addmod Objs/MAILBOX.OBJ 
addmod Objs/MAINTSK.OBJ 
addmod Objs/MAPUT.OBJ 
addmod Objs/MAUNLINK.OBJ 
addmod Objs/MBDOGET.OBJ 
addmod Objs/MBGET.OBJ 
addmod Objs/MBPUT.OBJ 
addmod Objs/MCLOCK.OBJ 
addmod Objs/MEMALLOC.OBJ 
addmod Objs/MEMBUF.OBJ 
addmod Objs/MGET.OBJ 
addmod Objs/MPUT.OBJ 
addmod Objs/OPSYS.OBJ 
addmod Objs/OSCHECK.OBJ 
addmod Objs/OSCONFIG.OBJ 
addmod Objs/PGET.OBJ 
addmod Objs/PGETCHAR.OBJ 
addmod Objs/PGETINT.OBJ 
addmod Objs/PGETLNG.OBJ 
addmod Objs/PGETSHRT.OBJ 
addmod Objs/PIPE.OBJ 
addmod Objs/PPUT.OBJ 
addmod Objs/PPUTBAK1.OBJ 
addmod Objs/PPUTBAK2.OBJ 
addmod Objs/PPUTBAK3.OBJ 
addmod Objs/PPUTBAK4.OBJ 
addmod Objs/PPUTBAK5.OBJ 
addmod Objs/PPUTCHAR.OBJ 
addmod Objs/PPUTINT.OBJ 
addmod Objs/PPUTLNG.OBJ 
addmod Objs/PPUTSHRT.OBJ 
addmod Objs/SCHED.OBJ 
addmod Objs/SEMAP.OBJ 
addmod Objs/SETPRI.OBJ 
addmod Objs/SIGNAL.OBJ 
addmod Objs/SSIGNAL.OBJ 
addmod Objs/STAKFREE.OBJ 
addmod Objs/STARTUP.OBJ 
addmod Objs/STASK.OBJ 
addmod Objs/SWAIT.OBJ 
addmod Objs/TASK.OBJ 
addmod Objs/TASKLIST.OBJ 
addmod Objs/THREAD1.OBJ 
addmod Objs/THREAD2.OBJ 
addmod Objs/THRUN.OBJ
addmod Objs/TRUN.OBJ 
addmod Objs/TSKINFO.OBJ 
addmod Objs/TSLEEP.OBJ 
addmod Objs/TSTART.OBJ 
addmod Objs/TSTOP.OBJ 
addmod Objs/UNBLK.OBJ 
addmod Objs/UNBLKALL.OBJ 
addmod Objs/XRAYOUT.OBJ 
SAVE
end

