//
//           File Name:  TPU_Channels.hxx
//         Description:
//		TPU channel address header.
//
//              Author:  Mark Giebler
//             Version:  1.2
// Date of Last Change:  6/6/94
//           Revisions:
//

#ifndef TPU_CHANNEL_ADDRESSES_HXX
#define TPU_CHANNEL_ADDRESSES_HXX

//-------------------------------------------------------------------
//TPU_CHANNEL_ADDRESSES

//-------------------------------------------------------------------
//OUTPUT CHANNELS

//-------------------------------------------------------------------
//INPUT CHANNELS


#endif
