SRC	= .
SRCP	= $(SRC)/
JOBS	= 1
CPPHOME	= /home/daffy/owc++/sun4
include ../build/sun.inc
Objs	= $(OBJ)/config.o
all: sun.make  $(OBJ)/sun4.time system.make io.make
	make iotest.make
	make systest.make
$(OBJ)/sun4.time: $(Objs) 
	ar r opsys.a $(Objs)
	ranlib opsys.a
	touch $(OBJ)/sun4.time
fast:
	make -f ../build/sun.mak &
	make -f ../build/system.mak &
	make -f ../build/io.mak &
	make -f ../build/iotest.mak CPPHOME=$(CPPHOME) &
	make -f ../build/systest.mak CPPHOME=$(CPPHOME) &
sun.make:
	make -f ../build/sun.mak
system.make:
	make -f ../build/system.mak
io.make:
	make -f ../build/io.mak
iotest.make:
	make -f ../build/iotest.mak CPPHOME=$(CPPHOME)
systest.make:
	make -f ../build/systest.mak CPPHOME=$(CPPHOME)
$(OBJ)/config.o: $(SRC)/config.c
config.s: config.c
	cc -S -I/home/daffy/allen/opsys/include -I/home/daffy/allen/opsys/sun/src config.c
