#!/bin/sh

copyFile()
{
  echo Copying $1 to $2
  echo /\* This file is a copy of file $1 \*/ > $2
  echo /\* DO NOT MODIFY THIS FILE! \*/ >> $2
  cat $1 >> $2
}

rm -f IO8.3/*
rm -f System8.3/*

copyFile IO/CPipe_CPipe.cpp IO8.3/CPipe1.cpp
copyFile IO/CPipe_doFlush.cpp IO8.3/CPipe2.cpp
copyFile IO/CPipe_get.cpp IO8.3/CPipe3.cpp
copyFile IO/CPipe_put.cpp IO8.3/CPipe4.cpp
copyFile IO/CPipe_putBack_char.cpp IO8.3/CPipe5.cpp
copyFile IO/CPipe_putBack_str.cpp IO8.3/CPipe6.cpp
copyFile IO/CmdHandler_CmdHandler.cpp IO8.3/CmdH1.cpp
copyFile IO/CmdHandler_check.cpp IO8.3/CmdH2.cpp
copyFile IO/CmdHandler_link.cpp IO8.3/CmdH3.cpp
copyFile IO/CmdHandler_parse.cpp IO8.3/CmdH4.cpp
copyFile IO/CmdHdr_CmdHdr.cpp IO8.3/CmdHd1.cpp
copyFile IO/CmdInt_CmdInt.cpp IO8.3/CmdI1.cpp
copyFile IO/CmdInt_execute.cpp IO8.3/CmdI2.cpp
copyFile IO/CmdPipe_CmdPipe.cpp IO8.3/CmdP1.cpp
copyFile IO/CmdPipe_doFlush.cpp IO8.3/CmdP2.cpp
copyFile IO/CmdPipe_get.cpp IO8.3/CmdP3.cpp
copyFile IO/CmdPipe_getTokn.cpp IO8.3/CmdP4.cpp
copyFile IO/CmdPipe_inNestLevel.cpp IO8.3/CmdP5.cpp
copyFile IO/CmdPipe_outNestLevel.cpp IO8.3/CmdP6.cpp
copyFile IO/CmdPipe_put.cpp IO8.3/CmdP7.cpp
copyFile IO/CmdPipe_putBack.cpp IO8.3/CmdP8.cpp
copyFile IO/CmdSub_CmdSub.cpp IO8.3/CmdS1.cpp
copyFile IO/CmdSub_execute.cpp IO8.3/CmdS2.cpp
copyFile IO/CmdSystem_CmdSystem.cpp IO8.3/CmdS3.cpp
copyFile IO/CmdTask_CmdTask.cpp IO8.3/CmdT1.cpp
copyFile IO/CmdTask_run.cpp IO8.3/CmdT2.cpp
copyFile IO/Command_Command.cpp IO8.3/Comm1.cpp
copyFile IO/Debug_Debug.cpp IO8.3/Debug1.cpp
copyFile IO/IOBuf_IOBuf.cpp IO8.3/IOBuf2.cpp
copyFile IO/IOBuf_bin.cpp IO8.3/IOBuf3.cpp
copyFile IO/IOBuf_dec.cpp IO8.3/IOBuf4.cpp
copyFile IO/IOBuf_doSetFill.cpp IO8.3/IOBuf5.cpp
copyFile IO/IOBuf_doSetw.cpp IO8.3/IOBuf6.cpp
copyFile IO/IOBuf_doSkip.cpp IO8.3/IOBuf7.cpp
copyFile IO/IOBuf_endl.cpp IO8.3/IOBuf8.cpp
copyFile IO/IOBuf_ends.cpp IO8.3/IOBuf9.cpp
copyFile IO/IOBuf_fail.cpp IO8.3/IOBuf10.cpp
copyFile IO/IOBuf_flush.cpp IO8.3/IOBuf11.cpp
copyFile IO/IOBuf_hex.cpp IO8.3/IOBuf12.cpp
copyFile IO/IOBuf_oct.cpp IO8.3/IOBuf13.cpp
copyFile IO/IOBuf_operatols_IOBuf.cpp IO8.3/IOBuf14.cpp
copyFile IO/IOBuf_operatorls_IOMANIPBOOL.cpp IO8.3/IOBuf15.cpp
copyFile IO/IOBuf_operatorls_IOMANIPCHAR.cpp IO8.3/IOBuf16.cpp
copyFile IO/IOBuf_operatorls_IOMANIPINT.cpp IO8.3/IOBuf17.cpp
copyFile IO/IOBuf_operatorls_char.cpp IO8.3/IOBuf18.cpp
copyFile IO/IOBuf_operatorls_int.cpp IO8.3/IOBuf19.cpp
copyFile IO/IOBuf_operatorls_long.cpp IO8.3/IOBuf20.cpp
copyFile IO/IOBuf_operatorls_short.cpp IO8.3/IOBuf21.cpp
copyFile IO/IOBuf_operatorls_str.cpp IO8.3/IOBuf22.cpp
copyFile IO/IOBuf_operatorls_uint.cpp IO8.3/IOBuf23.cpp
copyFile IO/IOBuf_operatorls_ulong.cpp IO8.3/IOBuf24.cpp
copyFile IO/IOBuf_operatorls_ushort.cpp IO8.3/IOBuf25.cpp
copyFile IO/IOBuf_operatorrs_IOBuf.cpp IO8.3/IOBuf26.cpp
copyFile IO/IOBuf_operatorrs_IOMANIPBOOL.cpp IO8.3/IOBuf27.cpp
copyFile IO/IOBuf_operatorrs_IOMANIPCHAR.cpp IO8.3/IOBuf28.cpp
copyFile IO/IOBuf_operatorrs_IOMANIPINT.cpp IO8.3/IOBuf29.cpp
copyFile IO/IOBuf_operatorrs_char.cpp IO8.3/IOBuf30.cpp
copyFile IO/IOBuf_operatorrs_int.cpp IO8.3/IOBuf31.cpp
copyFile IO/IOBuf_operatorrs_long.cpp IO8.3/IOBuf32.cpp
copyFile IO/IOBuf_operatorrs_short.cpp IO8.3/IOBuf33.cpp
copyFile IO/IOBuf_operatorrs_uint.cpp IO8.3/IOBuf34.cpp
copyFile IO/IOBuf_operatorrs_ulong.cpp IO8.3/IOBuf35.cpp
copyFile IO/IOBuf_opertorrs_ushort.cpp IO8.3/IOBuf36.cpp
copyFile IO/IOBuf_setFill.cpp IO8.3/IOBuf37.cpp
copyFile IO/IOBuf_setw.cpp IO8.3/IOBuf38.cpp
copyFile IO/IOBuf_skip.cpp IO8.3/IOBuf39.cpp
copyFile IO/IOBuf_spaceFill.cpp IO8.3/IOBuf40.cpp
copyFile IO/IOBuf_zeroFill.cpp IO8.3/IOBuf41.cpp
copyFile IO/IOString_IOString.cpp IO8.3/IOStr1.cpp
copyFile IO/IOString_doFlush.cpp IO8.3/IOStr2.cpp
copyFile IO/IOString_get.cpp IO8.3/IOStr3.cpp
copyFile IO/IOString_put.cpp IO8.3/IOStr4.cpp
copyFile IO/IOString_putBack.cpp IO8.3/IOStr5.cpp
copyFile IO/IOString_string.cpp IO8.3/IOStr6.cpp
copyFile IO/IOString_strlen.cpp IO8.3/IOStr7.cpp
copyFile IO/cnvtab.cpp IO8.3/cnvtab.cpp

copyFile System/Base_Base.cpp System8.3/Base1.cpp
copyFile System/Base_checkInit.cpp System8.3/Base2t.cpp
copyFile System/BitFlag_signal.cpp System8.3/BitF1.cpp
copyFile System/BitFlag_wait.cpp System8.3/BitF2.cpp
copyFile System/Bitflag_Bitflag.cpp System8.3/Bit3.cpp
copyFile System/Block_Block.cpp System8.3/Block1.cpp
copyFile System/Block_blockTask.cpp System8.3/Block2.cpp
copyFile System/Block_doUnBlockAll.cpp System8.3/Block3.cpp
copyFile System/Block_unBlockAll.cpp System8.3/Block4.cpp
copyFile System/Clock_Clock.cpp System8.3/Clock1.cpp
copyFile System/Clock_start.cpp System8.3/Clock2.cpp
copyFile System/Clock_stop.cpp System8.3/Clock3.cpp
copyFile System/ITask_ITask.cpp System8.3/ITask1.cpp
copyFile System/ITask_activate.cpp System8.3/ITask2.cpp
copyFile System/ITask_doSetPriority.cpp System8.3/ITask3.cpp
copyFile System/ITask_doTimout.cpp System8.3/ITask4.cpp
copyFile System/ITask_run.cpp System8.3/ITask5.cpp
copyFile System/ITask_setPriority.cpp System8.3/ITask6.cpp
copyFile System/ITask_sleep.cpp System8.3/ITask7.cpp
copyFile System/ITask_stackFree.cpp System8.3/ITask8.cpp
copyFile System/ITask_start.cpp System8.3/ITask9.cpp
copyFile System/ITask_stop.cpp System8.3/ITask10.cpp
copyFile System/ITask_unblockable.cpp System8.3/ITask11.cpp
copyFile System/MailBox_get.cpp System8.3/MailB1.cpp
copyFile System/MailBox_put.cpp System8.3/MailB2.cpp
copyFile System/Mailbox_Mailbox.cpp System8.3/Mailb3.cpp
copyFile System/MemAlloc_MemAlloc.cpp System8.3/MemA1.cpp
copyFile System/MemAlloc_get.cpp System8.3/MemA2.cpp
copyFile System/MemAlloc_linkFree.cpp System8.3/MemA3.cpp
copyFile System/MemAlloc_put.cpp System8.3/MemA4.cpp
copyFile System/MemAlloc_unlinkFree.cpp System8.3/MemA5.cpp
copyFile System/MemBuffer_MemBuffer.cpp System8.3/MemB1.cpp
copyFile System/MemBuffer_doGet.cpp System8.3/MemB2.cpp
copyFile System/MemBuffer_get.cpp System8.3/MemB3.cpp
copyFile System/MemBuffer_put.cpp System8.3/MemB4.cpp
copyFile System/OpSys_BlockInfo.cpp System8.3/OpSys1.cpp
copyFile System/OpSys_OpSys.cpp System8.3/OpSys2.cpp
copyFile System/OpSys_OpSys_buffer.cpp System8.3/OpSys3.cpp
copyFile System/OpSys_OpSys_stack.cpp System8.3/OpSys4.cpp
copyFile System/OpSys_check.cpp System8.3/OpSys5.cpp
copyFile System/OpSys_clockTick.cpp System8.3/OpSys6.cpp
copyFile System/OpSys_doSchedule.cpp System8.3/OpSys7.cpp
copyFile System/OpSys_exit.cpp System8.3/OpSys8.cpp
copyFile System/OpSys_exitLater.cpp System8.3/OpSys9.cpp
copyFile System/OpSys_lock.cpp System8.3/OpSys10.cpp
copyFile System/OpSys_mainTask.cpp System8.3/OpSys11.cpp
copyFile System/OpSys_schedule.cpp System8.3/OpSys12.cpp
copyFile System/OpSys_taskInfo.cpp System8.3/OpSys13.cpp
copyFile System/Pipe_Pipe.cpp System8.3/Pipe1.cpp
copyFile System/Pipe_get.cpp System8.3/Pipe2.cpp
copyFile System/Pipe_get_char.cpp System8.3/Pipe3.cpp
copyFile System/Pipe_get_int.cpp System8.3/Pipe4.cpp
copyFile System/Pipe_get_long.cpp System8.3/Pipe5.cpp
copyFile System/Pipe_get_short.cpp System8.3/Pipe6.cpp
copyFile System/Pipe_put.cpp System8.3/Pipe7.cpp
copyFile System/Pipe_putBack_char.cpp System8.3/Pipe8.cpp
copyFile System/Pipe_putBack_int.cpp System8.3/Pipe9.cpp
copyFile System/Pipe_putBack_long.cpp System8.3/Pipe10.cpp
copyFile System/Pipe_putBack_short.cpp System8.3/Pipe11.cpp
copyFile System/Pipe_putBack_void.cpp System8.3/Pipe12.cpp
copyFile System/Pipe_put_char.cpp System8.3/Pipe13.cpp
copyFile System/Pipe_put_int.cpp System8.3/Pipe14.cpp
copyFile System/Pipe_put_long.cpp System8.3/Pipe15.cpp
copyFile System/Pipe_put_short.cpp System8.3/Pipe16.cpp
copyFile System/STask_STask.cpp System8.3/STask1.cpp
copyFile System/STask_allocStack.cpp System8.3/STask2.cpp
copyFile System/Semaphore.cpp System8.3/Sem1.cpp
copyFile System/Semaphore_signal.cpp System8.3/Sem2.cpp
copyFile System/Semaphore_wait.cpp System8.3/Sem3.cpp
copyFile System/TaskList_TaskList.cpp System8.3/Task1.cpp
copyFile System/Thread_Thread1.cpp System8.3/Thread1.cpp
copyFile System/Thread_Thread2.cpp System8.3/Thread2.cpp
copyFile System/Thread_run.cpp System8.3/Thread3.cpp
copyFile System/assert.cpp System8.3/assert.cpp
